// list dependencies
const { src, dest, watch, series } = require('gulp');
const reinstall = require('gulp-reinstall');
const htmlMinify = require('html-minifier');
const sass = require('gulp-sass')(require('sass'));
const prefix = require('gulp-autoprefixer');
const minify = require('gulp-clean-css');
const terser = require('gulp-terser');
const imagemin = require('gulp-imagemin');
const imagewebp = require('gulp-webp');

const options = {
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    removeEmptyAttributes: true,
};


// create functions
// reinstall
function reinstallTask() {
    return src('package.json')
        .pipe(reinstall());
}

// html
function minifyHtml() {
    return src('src/*.html')
        .on('data', function(file) {
            const bufferFile = Buffer.from(htmlMinify.minify(file.contents.toString(), options))
            return file.contents = bufferFile
        })
        .pipe(dest('./'));
}
// fonts
function copyFonts() {
    return src('src/assets/fonts/*.{otf,eot,svg,ttf,woff,woff2}')
        .pipe(dest('./assets/fonts'));
}

// favicon
function copyFavicon() {
    return src('src/*.ico')
        .pipe(dest('./'));
}

// css
function minifyCss() {
    return src('src/assets/css/*.css')
        .on('data', function(file) {
            const bufferFile = Buffer.from(htmlMinify.minify(file.contents.toString(), options))
            return file.contents = bufferFile
        })
        .pipe(dest('./assets/css'));
}

// scss
function compileScss() {
  return src('src/assets/scss/*.scss')
    .pipe(sass())
    .pipe(prefix())
    .pipe(minify())
    .pipe(dest('./assets/css'));
}

// js
function minifyJs() {
    return src('src/assets/js/*.js')
        .pipe(terser())
        .pipe(dest('./assets/js'));
}

// images
function optimizeImages() {
    return src('src/assets/img/*.{jpg,jpeg,png,svg}')
        .pipe(imagemin([
            imagemin.mozjpeg({quality: 80, progressive: true}),
            imagemin.optipng({optimizationLevel: 2}),
        ]))
        .pipe(dest('./assets/img'));
}

// webp images
function webpImages() {
    return src('src/assets/img/*.{jpg,jpeg,png}')
        .pipe(imagewebp())
        .pipe(dest('./assets/img'));
}

// watch
function watchTask() {
    watch('src/*.html', minifyHtml);
    watch('src/*.ico', copyFavicon);
    watch('src/assets/fonts/*.{otf,eot,svg,ttf,woff,dwoff2}', copyFonts);
    watch('src/assets/css/*.css', minifyCss);
    watch('src/assets/scss/*.scss', compileScss);
    watch('src/assets/js/*.js', minifyJs);
    watch('src/assets/img/*.{jpg,jpeg,png,svg}', optimizeImages);
    watch('src/assets/img/*.{jpg,jpeg,png}', webpImages);
}

// default gulp
exports.default = series(
    reinstallTask,
    minifyHtml,
    copyFavicon,
    copyFonts,
    minifyCss,
    compileScss,
    minifyJs,
    optimizeImages,
    webpImages,
    watchTask
);

